### ISSUE TITLE
Building Friend Core failed

### ISSUE THREAD

**Issue by coreybruce** [FriendUPCloud/friendup#108]
Building Friend Core.
This can take up to several minutes depending on your machine.
Compilation log can be found in /mnt/Storage/Corey/friendup/compilation.log

A problem occurred during Friend Core compilation.
Please refer to compilation.log for more information.
Help can be found on Friend developer community forums at
https://developers.friendup.cloud
Installation unsuccessful.

[compilation.log](https://github.com/FriendUPCloud/friendup/files/3076118/compilation.log)

ld seems to not be able to find lssh_threads

I am using Manjaro

**Comment by titlestad** [comment]
@stefkosdev could probably help here.

**Comment by xet7** [comment]
There are dependencies missing from `install.sh` scripts, see install log.

[Example of adding dependencies for Ubuntu 18.04](https://github.com/Aperture-Development/friendup/commit/c18494f9e42cf4ba96c572ef66fa007ddcc8c284)

If you get modifications done to `install.sh` script so that some other distro like Manjaro also works, not just Ubuntu 16.04, please add pull request.

**Comment by titlestad** [comment]
Try our new documentation.
