### ISSUE TITLE
Ubuntu Disco Dingo - Support

### ISSUE THREAD

**Issue by TMajula** [FriendUPCloud/friendup#110]
Ubuntu Disco Dingo - Support for Ubuntu 19.04. 
Getting a message that version not found. Please see attached image

![Screenshot from 2019-05-28 17-46-46](https://user-images.githubusercontent.com/35775108/60991351-ae60d600-a34a-11e9-8f29-723a0e89b2a9.png)

**Comment by xet7** [comment]
There are dependencies missing from `install.sh` scripts, see install log.

[Example of adding dependencies for Ubuntu 18.04](https://github.com/Aperture-Development/friendup/commit/c18494f9e42cf4ba96c572ef66fa007ddcc8c284)

If you get modifications done to `install.sh` script so that some other distro also works, not just Ubuntu 16.04, please add pull request.

**Comment by titlestad** [comment]
The installer is being pensioned. We will give you an alternative route to get Friend installed once RC2 is finally out the door. :-)
