### ISSUE TITLE
USE_SELECT being developed?

### ISSUE THREAD

**Issue by johalun** [FriendUPCloud/friendup#40]
I had to do a lot of manual patching to get it working with USE_SELECT. Is this still being developed or are you planning to drop support for it in favor of epoll?

The long term goal would actually be to add support for kqueue on *BSD, which is preferable to select.

**Comment by stefkosdev** [comment]
Hey

Sorry for delay in reponse.
USE_SELECT was developed to allow us run Friend on windows (we need that in one of our projects).
We dont want drop support, because we know that some systems do not have epoll.
Currently its just not updated, because we are focused on other required feautures in our product.

**Comment by titlestad** [comment]
This is reenabled in 1.2rc1.
