### ISSUE TITLE
Feature Request: Add Clippy Javascript version

### ISSUE THREAD

**Issue by xet7** [FriendUPCloud/friendup#67]
Hi,
if I would make pull request about adding Clippy to Friend to help me write text document etc, would it be accepted?

https://www.smore.com/clippy-js

**Comment by sashafirsov** [comment]
The purpose of MS version is an interactive agent capable of invoking commands on served content. In Friendup terms, serving the application. The Windows application have a public "verbs" - named actions which been injected into Clippy content along with help text as links or buttons. Also Clippy was sensitive to application state change( I guess via anschient OLE interface ). 

In order to be functional, Clippy should be a controller for application engine. Able to receive the app state change, render matching content and run the action withing controlled application. 

As I see the Smore clippy is giving just an animation aspect. What about other parts? The question is addressed to friendup architect ( @thomaswollburg ? ).

**Comment by xet7** [comment]
@sashafirsov 

The link above https://www.smore.com/clippy-js is independent complete reimplementation in Javascript. There is no OLE etc. Everything can be controlled in Javascript. There could even be system-level setting about system messages and questions, are they normal Friend popups, or clippy-js with selectable character. Or alternatively, having clippy-js API for app-specific interactions.

**Comment by xet7** [comment]
For example, I would use this on Wekan, so Clippy would help with introducing Wekan settings, how to do Kanban, etc.

**Comment by titlestad** [comment]
Interesting! Why not! Would any of you reimplement this using our Widget class? It has a transparent mode, which would allow it to behave the same way, but playing nice with our window manager.

**Comment by xet7** [comment]
Related:
https://www.techrepublic.com/article/microsoft-reanimates-corpse-of-maligned-office-assistant-clippy-to-help-teams-compete-with-slack/
https://news.ycombinator.com/item?id=19451754
https://github.com/mampgmbh/microsoft-teams-clippy-app

**Comment by xet7** [comment]
I copied above repo to here https://github.com/xet7/microsoft-teams-clippy-app

**Comment by 344Clinton** [comment]
I, myself always kinda liked Clippy...at least the idea behind it. It should be implemented with a Friend flair though, not an actual Clippy 😀

**Comment by xet7** [comment]
I found this video, released 2 days ago:
Clippy: The Unauthorized Biography
https://www.youtube.com/watch?v=8bhjNvSSuLM

**Comment by xet7** [comment]
Warning, someone made Evil Clippy:
https://github.com/outflanknl/EvilClippy

**Comment by xet7** [comment]
Is there some safety measures in Friend Office or LibreOffice that would protect us from EvilClippy?

**Comment by titlestad** [comment]
Will not implement this at the current time. It's something a 3rd party developer can look into for sure.
